version: "2.5"

services:

  debezium:
    image: debezium/connect:2.1.1.Final
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: debezium-local
      CONFIG_STORAGE_TOPIC: debezium.configs
      OFFSET_STORAGE_TOPIC: debezium.offsets
      STATUS_STORAGE_TOPIC: debezium.statuses
      LOG_LEVEL: INFO
    restart: unless-stopped
    ports:
      - 8083:8083
      - 9012:9012
    networks:
      - local
    volumes:
      - ./etc/config.yml:/kafka/etc/config.yml

networks:
  local:
    external: true
