version: '2.5'

services:

  master:
    image: docker.io/bitnami/postgresql:14
    ports:
      - 5432:5432
    volumes:
      - ./master_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=SuperSecr3t
      - POSTGRESQL_DATABASE=postgres
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - local

  slave:
    image: docker.io/bitnami/postgresql:14
    ports:
      - 5433:5432
    depends_on:
      - master
    volumes:
      - ./slave_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=master
      - POSTGRESQL_PASSWORD=SuperSecr3t
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - local

networks:
  local:
    external: true
