version: '3.1'

services:

  secondary:
    image: docker.io/bitnami/postgresql:14
    ports:
      - 54320:5432
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=SuperSecr3t
      - POSTGRESQL_DATABASE=postgres
    volumes:
      - ./secondary_data:/bitnami/postgresql
      - ./slave_data/data/pg_wal:/bitnami/postgresql/archive

networks:
  local_common_network:
    external: true
