version: '3'

tasks:

  start:
    cmds:
    - docker compose up -d

  stop:
    cmds:
    - docker compose down --volumes

  start-secondary:
    cmds:
    - docker compose -f docker-compose-secondary-master.yml up -d

  stop-secondary:
    cmds:
    - docker compose -f docker-compose-secondary-master.yml down --volumes

  base-backup:
    cmds:
    - docker compose exec -it master pg_basebackup -D /tmp/postgresslave -S slave_1 -X stream -P -U replicator -Fp -R
    - docker compose cp master:/tmp/postgresslave ./
    - sudo cp -R ./postgresslave/* ./slave_data && sudo chmod -R 777 slave_data && sudo rm -rf ./postgresslave

  bash-master:
    cmds:
    - docker compose exec -it master bash

  shell-master:
    cmds:
    - echo SuperSecr3t | docker compose exec -iT master psql -U postgres -W -d postgres

  bash-secondary:
    cmds:
    - docker compose -f docker-compose-secondary-master.yml exec -it secondary bash

  bash-slave:
    cmds:
    - docker compose exec -it slave bash

  copy-from-master:
    cmds:
    - docker compose cp master:{{ .CLI_ARGS }} ./drafts
