version: '3.7'

services:

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_DATABASE_TYPE=postgresql
      - GF_DATABASE_HOST=postgresql
      - GF_DATABASE_USER=root
      - GF_DATABASE_PASSWORD=SuperSecr3t
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=SuperSecr3t
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - local

volumes:
  grafana_data:

networks:
  local:
    external: true
