version: '3'

tasks:

  start:
    cmds:
    - docker compose -f docker-compose.yml 
                     up -d --remove-orphans
  
  stop:
    cmds:
    - docker compose -f docker-compose.yml 
                     down
