source:
  kind: kafka
  topicPrefix: debezium.postgresql.dvdrental
  config:
    bootstrap.servers: kafka:9092
    group.id: debezium.postgresql.dvdrental
    key.converter: io.confluent.connect.avro.AvroConverter
    value.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://schema-registry:8085
    value.converter.schema.registry.url: http://schema-registry:8085
    poll.timeout.ms: 1000
    max.poll.records: 10000
  namingAdjusters:
    - class: dev.alluvial.source.kafka.naming.ChangingCaseNamingAdjuster
      case: lower
    - class: dev.alluvial.source.kafka.naming.MappingSchemaNamingAdjuster
      map:
        public: dvdrental

sink:
  kind: iceberg
  catalog:
    catalog-impl: org.apache.iceberg.hive.HiveCatalog
    warehouse: s3a://alluvial/.warehouse/
    uri: thrift://hive-metastore:9083
    io-impl: org.apache.iceberg.aws.s3.S3FileIO
    s3.endpoint: http://minio:9000
    s3.access-key-id: admin
    s3.secret-access-key: SuperSecr3t
    s3.path-style-access: true
  tableCreation:
    baseLocation: s3a://alluvial/cdc/dvdrental
    properties:
      write.format.default: PARQUET
      write.target-file-size-bytes: 134217728  # 128MiB
      engine.hive.enabled: true
      write.orc.compression-codec: snappy
      write.avro.compression-codec: snappy
      write.parquet.compression-codec: snappy
      write.delete.orc.compression-codec: snappy
      write.delete.avro.compression-codec: snappy
      write.delete.parquet.compression-codec: snappy
      write.metadata.compression-codec: gzip
      write.metadata.delete-after-commit.enabled: true
      write.metadata.previous-versions-max: 20
    partitionSpec:
      actor:
        - column: actor_id
          transform: truncate[50]
          name: actor_id_truncated
      film:
        - column: last_update
          transform: month
          name: lum

stream:
  kind: debezium
  connector: postgresql
  examineInterval: 3m
  idleTimeout: 30m
  commitBatchSize: 500
  commitTimespan: 15m
  rotateByDateInTz: "+7"

manager:
  namespace: [dvdrental]
  compactSnapshots:
    tz: "+7"
  expireOrphanSnapshots:
    enabled: false

metrics:
  exporters:
    - kind: prometheus
      properties:
        prometheus.bind: 0.0.0.0:9090
        prometheus.daemon: true
  commonTags:
    service: datalake.dvdrental
