clusterName: "opensearch-cluster"
nodeGroup: "master"

image:
  repository: "opensearchproject/opensearch"
  tag: 2.5.0

replicas: 3

masterService: "opensearch-cluster-master"

roles:
  - master
  - ingest
  - data
  - remote_cluster_client

resources:
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 4000m
    memory: 8Gi

rbac:
  create: true

persistence:
  enabled: true
  enableInitChown: true
  storageClass: ceph-rbd-ssd
  accessModes:
    - ReadWriteOnce
  size: 512Gi

protocol: https
httpPort: 9200
transportPort: 9300

sysctlVmMaxMapCount: 262144

sysctlInit:
  enabled: true

security:
  tls:
    clusterIssuerName: ca-issuer
    keystore: RCZJJ6951CrhdvZJiGgBWuq3wtGgTzXD1pHnMk/n5K5RXaHu4UkbuAHwtgdFTjAH
    commonName: opensearch-cluster-master.opensearch.svc

  authn:
    type: oidc  # password, oidc

    oidc:
      connect_url: https://keycloak.tekodata.com/realms/data/.well-known/openid-configuration
      client_id: opensearch
      client_secret: dbSKHfVHvjAWAbADbe2tvwc9xvotqH7y
      principal_field: preferred_username
      base_redirect_url: https://opensearch.tekodata.com

dashboards:

  replicaCount: 1

  image:
    repository: "opensearchproject/opensearch-dashboards"
    tag: 2.5.0

  service:
    type: ClusterIP
    port: 5601
    httpPortName: http

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
