version: "2.5"

services:

  alluvial-stream:
    image: hub.teko.vn/dataops/alluvial:v0.12.1
    environment:
      AWS_REGION: aws-global
    command:
      - alluvial
      - stream
      - /etc/alluvial/config.yaml
    # restart: unless-stopped
    # ports:
      # - 9090:9090
    volumes:
      - ./config/config.yaml:/etc/alluvial/config.yaml
    networks:
      - local

  alluvial-manager:
    image: hub.teko.vn/dataops/alluvial:v0.12.1
    environment:
      AWS_REGION: aws-global
    command:
      - alluvial
      - manage
      - /etc/alluvial/config.yaml
    # restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - local
    volumes:
      - ./config/config.yaml:/etc/alluvial/config.yaml

networks:
  local:
    external: true
