repositories:

- name: bitnami
  url:  https://charts.bitnami.com/bitnami

- name: trino
  url:  https://charts.bitnami.com/bitnami

helmDefaults:
  wait: true
  force: true
  verify: true
  createNamespace: true
  timeout: 600

helmfiles:
# - path: compute/helm/trino/deploy/helmfile.yaml

- path: storage/helm/postgresql/helmfile.yaml

- path: serving/helm/keycloak/helmfile.yaml

