version: '3'

includes:
  docker:
    taskfile: ./tasks/Taskdocker.yml
    optional: false
  helm:
    taskfile: ./tasks/Taskhelm.yml
    optional: false
  addons:
    taskfile: ./tasks/Taskaddons.yaml
    optional: false
  k8s:
    taskfile: ./tasks/Taskk8s.yml
    optional: false
