{{- if and .Values.security.enabled (not .Values.security.tls.useDemoCert) }}
{{- $tls := .Values.security.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $tls.commonName }}
  namespace: opensearch
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  duration:    2160h # 90d
  renewBefore: 360h  # 15d
  subject:
    organizations: [{{ $tls.organizations }}]
    countries: [{{ $tls.countries }}]
    organizationalUnits: [{{ $tls.organizationalUnits }}]
    localities: [{{ $tls.localities }}]
  isCA: false
  usages:
  - server auth
  - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  commonName: {{ $tls.commonName }}
  dnsNames:
  - {{ $tls.commonName }}
  - {{ template "opensearch.masterService" . }}-headless
  issuerRef:
    name:  {{ $tls.clusterIssuerName }}
    kind:  ClusterIssuer
    group: cert-manager.io
  secretName: {{ $tls.commonName }}-tls
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key:  keystore.key
        name: opensearch-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-secret
  namespace: opensearch
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  keystore.key: {{ $tls.keystore }}
{{- end }}
