version: '3'

services:
  namenode:
    image: sondn1/hadoop-namenode:0.1.0-hadoop_3.3.1
    networks:
      - hadoop
    volumes:
      - namenode:/hadoop/dfs/name
    ports:
      - 9870:9870
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  datanode:
    image: sondn1/hadoop-datanode:0.1.0-hadoop_3.3.1
    networks:
      - hadoop
    volumes:
      - datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure

  resourcemanager:
    image: sondn1/hadoop-resourcemanager:0.1.0-hadoop_3.3.1
    networks:
      - hadoop
    depends_on:
      - namenode
      - datanode
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      disable: true

  nodemanager:
    image: sondn1/hadoop-nodemanager:0.1.0-hadoop_3.3.1
    networks:
      - hadoop
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  historyserver:
    image: sondn1/hadoop-historyserver:0.1.0-hadoop_3.3.1
    networks:
      - hadoop
    volumes:
      - historyserver:/hadoop/yarn/timeline
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    deploy:
      mode: replicated
      replicas: 1

volumes:
  datanode:
  namenode:
  historyserver:

networks:
  hadoop:
