version: '3'

tasks:
  start:
    env:
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: SuperSecr3t
      _PIP_ADDITIONAL_REQUIREMENTS:
      AIRFLOW_IMAGE_NAME: apache/airflow:2.3.2
      AIRFLOW_UID: 1000
    cmds:
    - source env.sh
    - docker compose up -d --remove-orphans

  stop:
    cmds:
    - docker compose down --volumes
