version: '3'

env:
  DB_TYPE: '{{.DB_TYPE | default "mysql"}}'

tasks:

  start:
    cmds:
    - docker compose up -d --remove-orphans

  stop:
    cmds:
    - docker compose down --volumes

  bash:
    cmds:
    - docker compose exec -it {{ .CLI_ARGS }} bash

  create-connector:
    cmds:
    - curl -i -X POST http://localhost:8083/connectors/
              -H "Accept:application/json"
              -H "Content-Type:application/json"
              -d @./connectors/connector-${DB_TYPE}.json

  delete-connector:
    cmds:
    - curl -i -X DELETE localhost:8083/connectors/{{ .CLI_ARGS }}
              -H "Accept:application/json"

  get-connector:
    cmds:
    - curl -i -X GET localhost:8083/connectors/{{ .CLI_ARGS }}
              -H "Accept:application/json"

  list-connectors:
    cmds:
    - curl -i -X GET localhost:8083/connectors
              -H "Accept:application/json"

  restart-connector:
    cmds:
    - curl -i -X POST localhost:8083/connectors/{{ .CLI_ARGS }}/restart
              -H "Accept:application/json"

  update-connector:
    cmds:
    - curl -i -X PUT http://localhost:8083/connectors/{{ .CLI_ARGS }}/config
              -H "Accept:application/json"
              -H "Content-Type:application/json"
              -d @./connectors/connector-${DB_TYPE}-update.json


