version: '3.7'

services:

  trino:
    image: trinodb/trino:406
    ports:
      - 18080:8080
    volumes:
      - ./config:/etc/trino
      - ./etc:/etc/misc
      - trino_data:/data
    networks:
      - local

  events-handler:
    image: jazzdd/alpine-flask:python3
    ports:
      - 18081:80
    volumes:
      - ./etc/events-handler.py:/app/app.py
    networks:
      - local

volumes:
  trino_data:

networks:
  local:
    external: true
