version: '3.7'

services:

  trino:
    image: sondn1/trino:408
    ports:
      - 18080:8080
    volumes:
      - ./config:/etc/trino
      - ./etc:/etc/misc
      - trino_data:/data
    networks:
      - local

volumes:
  trino_data:

networks:
  local:
    external: true
