version: '3.7'

services:
  trino:
    image: trinodb/trino:387
    ports:
      - 18080:8080
    volumes:
      - ./configurations:/etc/trino
      - ./catalogs/jmx.properties:/etc/trino/catalog/jmx.properties
      - ./catalogs/memory.properties:/etc/trino/catalog/memory.properties
      - ./catalogs/tpcds.properties:/etc/trino/catalog/tpcds.properties
      - ./catalogs/tpch.properties:/etc/trino/catalog/tpch.properties
      - ./catalogs/kafka.properties:/etc/trino/catalog/kafka.properties
      - trino_data:/data
    networks:
      - local_common_network

volumes:
  trino_data:

networks:
  local_common_network:
    external: true
