repositories:
- name: bitnami
  url:  https://charts.bitnami.com/bitnami
- name: akhq
  url:  https://akhq.io/
- name: prometheus-community
  url:  https://prometheus-community.github.io/helm-charts
- name: strimzi
  url:  https://strimzi.io/charts/

helmDefaults:
  wait: true
  force: true
  verify: true
  createNamespace: true
  timeout: 600

helmfiles:

- path: ../../../kubernetes/databases/mysql/helmfile.yaml
- path: ../../../kubernetes/databases/postgresql/helmfile.yaml
- path: ../../../kubernetes/operators/strimzi/helmfile.yaml
- path: ../../../kubernetes/storage/zookeeper/helmfile.yaml
- path: ../../../kubernetes/storage/kafka/helmfile.yaml
- path: ../../../kubernetes/storage/minio/helmfile.yaml
- path: ../../../kubernetes/warehouse/hive/helmfile.yaml
