version: '3'

tasks:

  start:
    cmds:
    - helmfile apply
    - kubectl -n kafka apply -k ./

  stop:
    cmds:
    - helmfile destroy
    - kubectl -n kafka delete -k ./

  load-images:
    cmds:
    # - minikube image load bitnami/schema-registry:7.1.3-debian-11-r11
    # - minikube image load hub.teko.vn/dataops/hive:3.1.3
    # - minikube image load hub.teko.vn/dataops/alluvial:v0.10.2
    - minikube image load hub.teko.vn/dataops/kafka/debezium:1.9.1-kafka-2.8.1

  create-ingestors:
    dir: ./ingestors
    cmds:
    - helmfile apply

  create-connectors:
    dir: ./connectors
    cmds:
    - kubectl -n kafka apply -k ./

  delete-connector:
    cmds:
    - kubectl -n kafka delete KafkaConnector {{ .CLI_ARGS }}

  list-connectors:
    cmds:
    - kubectl -n kafka get KafkaConnector
