version: '3'

services:

  keycloak:
    image: docker.io/bitnami/keycloak:19
    environment:
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: SuperSecr3t
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_MANAGEMENT_USER: manager
      KEYCLOAK_MANAGEMENT_PASSWORD: SuperSecr3t
    ports:
      - 8080:8080
    networks:
      - local

volumes:
  postgres_data:
      driver: local

networks:
  local:
    external: true
