version: '3.1'

services:

  postgresql:
    image: postgres:14.3-alpine3.16
    restart: unless-stopped
    command:
      - -c
      - wal_level=logical
      - -c
      - wal_compression=on
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperSecr3t
    volumes:
      - ./sample/app-init:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_common_network

volumes:
  postgres_data:

networks:
  local_common_network:
    external: true
