version: '3.7'

services:
  minio:
    image: minio/minio
    command: [ server, --address=:9000, --console-address=:9001, /data ]
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: SuperSecr3t
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    networks:
      - local

volumes:
  minio_data:

networks:
  local:
    external: true

