version: '3.1'

services:

  # postgresql:
  #   image: postgres:15.1
  #   restart: unless-stopped
  #   command:
  #     - -c
  #     - wal_level=logical
  #     - -c
  #     - wal_compression=on
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: SuperSecr3t
  #   volumes:
  #     - ./sample:/docker-entrypoint-initdb.d
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - local

  postgresql:
    image: bitnami/postgresql:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperSecr3t
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - local

  pgbouncer:
    image: docker.io/bitnami/pgbouncer:1.18.0
    ports:
      - 6432:6432
    environment:
      POSTGRESQL_HOST: postgresql
      # PGBOUNCER_AUTH_TYPE: trust
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: SuperSecr3t
      PGBOUNCER_POOL_MODE: session # session | transaction | statement
      PGBOUNCER_MAX_CLIENT_CONN: 120
      PGBOUNCER_MAX_DB_CONNECTIONS: 512
      PGBOUNCER_DEFAULT_POOL_SIZE: 100
      PGBOUNCER_IGNORE_STARTUP_PARAMETERS: extra_float_digits
    volumes:
      - ./config/:/bitnami/pgbouncer/conf/
    networks:
      - local

volumes:
  postgres_data:

networks:
  local:
    external: true
