version: '3.1'

services:

  postgresql:
    image: postgres:14.5
    restart: unless-stopped
    command:
      - -c
      - wal_level=logical
      - -c
      - wal_compression=on
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperSecr3t
    volumes:
      - ./sample/app-init:/docker-entrypoint-initdb.d/
      - ./sample/dvdrental-db/dvdrental.sh:/docker-entrypoint-initdb.d/dvdrental.sh
      - ./sample/dvdrental-db/dvdrental.tar:/docker-entrypoint-initdb.d/dvdrental.tar
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local

volumes:
  postgres_data:

networks:
  local:
    external: true
