version: "3.7"

services:
  opensearch:
    image: opensearchproject/opensearch:2.5.0
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: true
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
      DISABLE_INSTALL_DEMO_CONFIG: true
      DISABLE_SECURITY_PLUGIN: true
    volumes:
      - opensearch_data:/usr/share/opensearch/data
      - ./config/opensearch/security/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
      - ./config/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./config/opensearch/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./config/opensearch/node-key.pem:/usr/share/opensearch/config/node-key.pem
      - ./config/opensearch/node.pem:/usr/share/opensearch/config/node.pem
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - local

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0
    environment:
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    ports:
      - 5601:5601
    volumes:
      - ./config/dashboard/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    networks:
      - local

volumes:
  opensearch_data:

networks:
  local:
    external: true
