version: "3.7"

services:
  opensearch:
    image: opensearchproject/opensearch:2.4.1
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: true
      DISABLE_SECURITY_PLUGIN: true
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - local

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.4.1
    environment:
      OPENSEARCH_HOSTS: http://opensearch:9200
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    ports:
      - 5601:5601
    networks:
      - local

volumes:
  opensearch_data:

networks:
  local:
    external: true
