version: '3'

tasks:

  start:
    cmds:
    - docker compose up -d --remove-orphans

  stop:
    cmds:
    - docker compose down --volumes

  gen-cert:
    dir: config/opensearch
    cmds:
    - sh self-signed.sh

  start-multinodes:
    cmds:
    - docker compose -f multi-nodes.yml up -d --remove-orphans

  stop-multinodes:
    cmds:
    - docker compose -f multi-nodes.yml down --volumes

