version: "3"

services:

  hive-server:
    image: $REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION
    restart: unless-stopped
    depends_on:
      - hive-metastore
    ports:
      - 10000:10000
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    volumes:
      - ./config/hadoop/hdfs-site.xml:/opt/hadoop/apache-hadooop-bin/etc/hadoop/hdfs-site.xml
      - ./config/hive/hive-site.xml:/opt/hive/apache-hive-bin/conf/hive-site.xml
    networks:
      - local

  hive-metastore:
    image: $REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION
    command: hive --service metastore --verbose --hiveconf hive.root.logger=INFO,console
    restart: unless-stopped
    depends_on:
      - init_metastore_db
    ports:
      - 9083:9083
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    volumes:
      - ./config/hadoop/hdfs-site.xml:/opt/hadoop/apache-hadooop-bin/etc/hadoop/hdfs-site.xml
      - ./config/hive/hive-site.xml:/opt/hive/apache-hive-bin/conf/hive-site.xml
    networks:
      - local

  init_metastore_db:
    image: $REPOSITORY/$IMAGE_NAME:$IMAGE_VERSION
    command: >
      schematool -url jdbc:postgresql://postgresql:5432/metastore \
                 -dbType postgres -userName metastore -passWord SuperSecr3t \
                 -driver org.postgresql.Driver \
                 -initSchema \
                 --verbose
    profiles:
      - init
    networks:
      - local

networks:
  local:
    external: true
