version: "3"

services:

  hive-server:
    image: sondn1/hive:0.1.0
    depends_on:
      - hive-metastore
    ports:
      - 10000:10000
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    volumes:
      - ./configurations/hadoop/:/opt/hadoop/hadoop-3.3.1/etc/hadoop/
    networks:
      - local

  hive-metastore:
    image: sondn1/hive:0.1.0
    command: hive --service metastore --verbose --hiveconf hive.root.logger=INFO,console
    depends_on:
      - init_metastore_db
    ports:
      - 9083:9083
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
    volumes:
      - ./configurations/hadoop/:/opt/hadoop/hadoop-3.3.1/etc/hadoop/
    networks:
      - local

  init_metastore_db:
    image: sondn1/hive:0.1.0
    command: >
      schematool -url jdbc:postgresql://postgresql:5432/metastore \
                 -dbType postgres -userName hive -passWord SuperSecr3t \
                 -driver org.postgresql.Driver \
                 -initSchema \
                 --verbose
    depends_on:
      - postgresql
    networks:
      - local

networks:
  local:
    external: true
