version: '3'

vars:
  HIVE_VERSION: '{{.HIVE_VERSION | default "0.1.0"}}'

tasks:

  start:
    cmds:
    - docker compose up -d --remove-orphans

  stop:
    cmds:
    - docker compose down

  build:
    cmds:
    - docker build --tag sondn1/hive:{{ .HIVE_VERSION }} .

  push:
    cmds:
    - docker push sondn1/hive:{{ .HIVE_VERSION }}

  publish:
    cmds:
    - task: build
    - task: push
