{{- if .Values.security.enabled }}
{{- $authn := .Values.security.authn }}
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    authc:

      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          {{- if eq $authn.type "oidc" }}
          challenge: false
          {{- else }}
          challenge: true
          {{- end }}
        authentication_backend:
          type: internal

      {{- if eq $authn.type "oidc" }}
      {{- $oidc := $authn.oidc }}
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: {{ $oidc.principal_field }}
            roles_key: roles
            openid_connect_url: {{ $oidc.connect_url }}
        authentication_backend:
          type: noop
      {{- end }}
{{- end }}
