version: '3'

# Services:
# - BI: superset
# - Computation: airflow datahub debezium nifi spark trino
# - Databases: mongo mysql neo4j postgresql rabbitmq redis
# - Monitoring: grafana prometheus
# - Security: keycloak vault
# - Storage: elasticsearch hadoop kafka minio zookeeper
# - Warehouse: hive

env:
  SERVICES: |


includes:
  # Base
  base:
    taskfile: ./base/Taskfile.yml
    dir: ./base

  # BI
  superset:
    taskfile: ./bi/superset/Taskfile.yml
    dir: ./bi/superset

  # Computation
  airflow:
    taskfile: ./computation/airflow/Taskfile.yml
    dir: ./computation/airflow
  datahub:
    taskfile: ./computation/datahub/Taskfile.yml
    dir: ./computation/datahub
  debezium:
    taskfile: ./computation/debezium/Taskfile.yml
    dir: ./computation/debezium
  nifi:
    taskfile: ./computation/nifi/Taskfile.yml
    dir: ./computation/nifi
  spark:
    taskfile: ./computation/spark/Taskfile.yml
    dir: ./computation/spark
  trino:
    taskfile: ./computation/trino/Taskfile.yml
    dir: ./computation/trino

  # Databases
  mongo:
    taskfile: ./databases/mongo/Taskfile.yml
    dir: ./databases/mongo
  mysql:
    taskfile: ./databases/mysql/Taskfile.yml
    dir: ./databases/mysql
  neo4j:
    taskfile: ./databases/neo4j/Taskfile.yml
    dir: ./databases/neo4j
  postgresql:
    taskfile: ./databases/postgresql/Taskfile.yml
    dir: ./databases/postgresql
  rabbitmq:
    taskfile: ./databases/rabbitmq/Taskfile.yml
    dir: ./databases/rabbitmq
  redis:
    taskfile: ./databases/redis/Taskfile.yml
    dir: ./databases/redis

  # Monitoring
  grafana:
    taskfile: ./monitoring/grafana/Taskfile.yml
    dir: ./monitoring/grafana
  prometheus:
    taskfile: ./monitoring/prometheus/Taskfile.yml
    dir: ./monitoring/prometheus

  # Security
  keycloak:
    taskfile: ./security/keycloak/Taskfile.yml
    dir: ./security/keycloak
  vault:
    taskfile: ./security/vault/Taskfile.yml
    dir: ./security/vault

  # Storage
  elasticsearch:
    taskfile: ./storage/elasticsearch/Taskfile.yml
    dir: ./storage/elasticsearch
  hadoop:
    taskfile: ./storage/hadoop/Taskfile.yml
    dir: ./storage/hadoop
  kafka:
    taskfile: ./storage/kafka
    dir: ./storage/kafka
  minio:
    taskfile: ./storage/minio/Taskfile.yml
    dir: ./storage/minio
  opensearch:
    taskfile: ./storage/opensearch/Taskfile.yml
    dir: ./storage/opensearch
  zookeeper:
    taskfile: ./storage/zookeeper/Taskfile.yml
    dir: ./storage/zookeeper

  # Warehouse
  hive:
    taskfile: ./warehouse/hive/Taskfile.yml
    dir: ./warehouse/hive

  # Other
  postgrest:
    taskfile: ./other/postgrest/Taskfile.yml
    dir: ./other/postgrest
  strapi:
    taskfile: ./other/strapi/Taskfile.yml
    dir: ./other/strapi

tasks:

  start-services:
    cmds:
    - |
      for SERVICE in ${SERVICES[@]}; do
        # task $SERVICE:start
        echo $SERVICE
      done

  stop-services:
    cmds:
    - |
      for SERVICE in ${SERVICES[@]}; do
        task $SERVICE:stop
      done

  create-local-network:
    env:
      DEFAULT_NETWORK: '{{.DEFAULT_NETWORK | default "local"}}'
    cmds:
    - docker network create $DEFAULT_NETWORK

  rm-containers:
    cmds:
    - docker rm --force $(docker ps -aq)

  rm-volumes:
    cmds:
    - docker volume rm $(docker volume ls -q)

  prune:
    cmds:
    - docker system prune -af
