version: "2"

services:

  debezium:
    image: quay.io/debezium/connect:1.9.3.Final
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: dbz-1
      CONFIG_STORAGE_TOPIC: debezium.configs
      OFFSET_STORAGE_TOPIC: debezium.offsets
      STATUS_STORAGE_TOPIC: debezium.statuses
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    depends_on:
      - kafka
      - schema-registry
    ports:
      - 8083:8083

networks:
  default:
    name: local_common_network
    external: true
