{{- $service := .Values.service }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "common.serviceName" . }}
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
{{- if $service.labels }}
{{ toYaml $service.labels | indent 4 }}
{{- end }}
  annotations:
{{ toYaml $service.annotations | indent 4 }}
spec:
  type: {{ $service.type }}
  selector:
    {{- include "opensearch.selectorLabels" . | nindent 4 }}
  ports:
  - name: {{ $service.httpPortName | default "http" }}
    protocol: TCP
    port: {{ .Values.httpPort }}
{{- if $service.nodePort }}
    nodePort: {{ $service.nodePort }}
{{- end }}
  - name: {{ $service.transportPortName | default "transport" }}
    protocol: TCP
    port: {{ .Values.transportPort }}
{{- if $service.loadBalancerIP }}
  loadBalancerIP: {{ $service.loadBalancerIP }}
{{- end }}
{{- with $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | indent 4 }}
{{- end }}
{{- if $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $service.externalTrafficPolicy }}
{{- end }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "common.serviceName" . }}-headless
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
{{- if $service.labelsHeadless }}
{{ toYaml $service.labelsHeadless | indent 4 }}
{{- end }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
{{- if $service.headless.annotations }}
{{ toYaml $service.headless.annotations | indent 4 }}
{{- end }}
spec:
  clusterIP: None # This is needed for statefulset hostnames like opensearch-0 to resolve
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
    {{- include "opensearch.selectorLabels" . | nindent 4 }}
  ports:
  - name: {{ $service.httpPortName | default "http" }}
    port: {{ .Values.httpPort }}
  - name: {{ $service.transportPortName | default "transport" }}
    port: {{ .Values.transportPort }}
