# Use root/example as user/password credentials
version: '2.5'

services:

  mysql:
    image: mysql:8.0
    command:
      - --gtid-mode=ON
      - --enforce_gtid_consistency=ON
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecr3t
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./sample:/docker-entrypoint-initdb.d/
      - mysql_data:/var/lib/mysql
    networks:
      - local

volumes:
  mysql_data:

networks:
  local:
    external: true
