version: '3'

vars:
  NAMESPACE: trino

tasks:
  install-cert:
    cmds:
    - kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml

  apply-cert:
    cmds: 
    - kubectl apply -n trino -f ../deploy/trino-certificate.yaml

