version: "2"

services:

  akhq:
    image: tchiotludo/akhq
    ports:
      - 8080:8080
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
      - schema-registry
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-local:
              properties:
                bootstrap.servers: kafka-0:9092,kafka-1:9092,kafka-2:9092
              schema-registry:
                url: "http://schema-registry:8085"
              debezium-connect:
                url: "http://debezium:8083"
