version: "2"

services:

  akhq:
    image: tchiotludo/akhq
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - schema-registry
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-local:
              properties:
                bootstrap.servers: kafka:9092
              schema-registry:
                url: "http://schema-registry:8085"
              connect:
                - name: debezium
                  url: http://debezium:8083
    networks:
      - local_common_network

networks:
  local_common_network:
    external: true