version: '2.5'

services:

  jupyter:
    image: jupyter/pyspark-notebook:2023-03-03
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes:
      - ./workspace:/home/jovyan
    networks:
      - local

networks:
  local:
    external: true
