version: "2.5"

services:

  akhq:
    image: tchiotludo/akhq
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-local:
              properties:
                bootstrap.servers: kafka:9092
    networks:
      - local_common_network

networks:
  local_common_network:
    external: true
