version: "2.5"

services:

  kafka:
    image: docker.io/bitnami/kafka:3.2
    restart: unless-stopped
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - local_common_network

  akhq:
    image: tchiotludo/akhq
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka-local:
              properties:
                bootstrap.servers: kafka:9092

volumes:
  kafka_data:
    driver: local

networks:
  local_common_network:
    external: true
