version: '2'
services:
  # redpanda:
  #   image: vectorized/redpanda:v22.1.3
  #   restart: unless-stopped
  #   command:
  #     - redpanda start
  #     - --smp 1
  #     - --overprovisioned
  #     - --node-id 0
  #     - --kafka-addr http://kafka:9092
  #     - --advertise-kafka-addr http://kafka:9092
  #     - --pandaproxy-addr 0.0.0.0:8082
  #     - --advertise-pandaproxy-addr localhost:8082
  #   ports:
  #     - 8081:8081
  #     - 8082:8082
  #     - 9092:9092
  #     - 29092:29092
  #   networks:
  #     - local

  console:
    image: docker.redpanda.com/vectorized/console:master-173596f
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:9092"]
          schemaRegistry:
            enabled: false
            urls: ["http://redpanda:8081"]
        connect:
          enabled: true
          clusters:
            - name: debezium
              url: http://debezium:8083
    ports:
      - 8082:8080
    networks:
      - local

networks:
  local:
    external: true
