version: "2.5"

services:

  kafka:
    image: docker.io/bitnami/kafka:3.3.1
    restart: unless-stopped
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092

      ## Enable kafka with zookeeper
      # KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181

      ## Enable Kafka's KRAFT mode
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093

    networks:
      - local

  schema-registry:
    image: confluentinc/cp-schema-registry
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 8085:8085
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:9092'
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8085'
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: 'INFO'
    networks:
      - local

  # akhq:
  #   image: tchiotludo/akhq
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   environment:
  #     AKHQ_CONFIGURATION: |
  #       akhq:
  #         connections:
  #           kafka-local:
  #             properties:
  #               bootstrap.servers: kafka:9092
  #   networks:
  #     - local

  console:
    image: docker.redpanda.com/vectorized/console:master-173596f
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:9092"]
          schemaRegistry:
            enabled: false
            urls: ["http://redpanda:8081"]
        connect:
          enabled: true
          clusters:
            - name: debezium
              url: http://debezium:8083
    ports:
      - 8082:8080
    networks:
      - local

volumes:
  kafka_data:
    driver: local

networks:
  local:
    external: true
