repositories:
- name: bitnami
  url:  https://charts.bitnami.com/bitnami
- name: akhq
  url:  https://akhq.io/
- name: prometheus-community
  url:  https://prometheus-community.github.io/helm-charts
- name: strimzi
  url:  https://strimzi.io/charts/
- name: spark-operator
  url:  https://googlecloudplatform.github.io/spark-on-k8s-operator
- name: fluentbit
  url: https://fluent.github.io/helm-charts

helmDefaults:
  wait: true
  force: true
  verify: true
  createNamespace: true
  timeout: 600

helmfiles:

# - path: addons/cert-manager/helmfile.yaml
# - path: addons/metrics-server/helmfile.yaml

# - path: computation/airflow/helmfile.yaml
# - path: computation/trino/helmfile.yaml
# - path: computation/fluentbit/helmfile.yaml

# - path: databases/mysql/helmfile.yaml
# - path: databases/postgresql/helmfile.yaml
# - path: databases/redis/helmfile.yaml

# - path: operators/strimzi/helmfile.yaml
# - path: operators/spark/helmfile.yaml

# - path: monitoring/prometheus/helmfile.yaml
# - path: monitoring/grafana/helmfile.yaml

# - path: security/keycloak/helmfile.yaml

# - path: storage/kafka/helmfile.yaml
# - path: storage/minio/helmfile.yaml
# - path: storage/opensearch/helmfile.yaml
# - path: storage/zookeeper/helmfile.yaml

# - path: warehouse/hive/helmfile.yaml
