version: '3'

vars:
  NAMESPACE: '{{.NAMESPACE | default "default"}}'
  RELEASE: '{{.RELEASE | default "funny"}}'
  VALUES: '{{.VALUES | default "./values.yaml"}}'
  CLUSTER_MOUNTPATH: '{{.CLUSTER_MOUNTPATH | default "/data1/minikube"}}'
  CLUSTER_MEMORY: '{{.CLUSTER_MEMORY | default "8192"}}'
  CLUSTER_CPUS: '{{.CLUSTER_CPUS | default "4"}}'

tasks:

  minikube-up:
    cmds:
    - minikube start --driver=virtualbox
                     --mount
                     --mount-string="/data1/minikube:{{ .CLUSTER_MOUNTPATH }}"
                     --memory {{ .CLUSTER_MEMORY }}
                     --cpus {{ .CLUSTER_CPUS }}
                     --nodes 1
    - minikube addons enable ingress

  minikube-down:
    cmds:
    - minikube stop --all

  minikube-delete:
    cmds:
    - minikube delete

  deploy:
    cmds:
    - helmfile apply

  destroy:
    cmds:
    - helmfile destroy

  deploy-kustomize:
    cmds:
    - kubectl apply -k ./

  destroy-kustomize:
    cmds:
    - kubectl delete -k ./

  deploy-all:
    cmds:
    - task: deploy-kustomize
    - helmfile apply

  destroy-all:
    cmds:
    - helmfile destroy
    - task: destroy-kustomize

  template:
    cmds:
    - helmfile template --output-dir=./build

  diff:
    cmds:
    - helm diff upgrade {{.RELEASE}} .
        --namespace={{.NAMESPACE}}
        --values={{.VALUES}}
        --allow-unreleased

  apply:
    cmds:
    - helm upgrade --install {{.RELEASE}} .
        --namespace={{.NAMESPACE}}
        --values={{.VALUES}}
        --create-namespace

  show:
    cmds:
    - kubectl --namespace={{.NAMESPACE}} get pod
        -l app.kubernetes.io/instance={{.RELEASE}}
