image:
  registry: docker.io
  repository: bitnami/mysql
  tag: 8.0.30-debian-11-r6

architecture: standalone

auth:
  rootPassword: "SuperSecr3t"
  createDatabase: true
  database: "mydb"
  username: "myuser"
  password: "SuperSecr3t"
  replicationUser: replicator
  replicationPassword: "SuperSecr3t"

initdbScripts:
  sakila.sh: |
    #!/bin/bash
    SCHEMA_DOWNLOAD_LINK=https://raw.githubusercontent.com/sondn98/hilt/master/kubernetes/databases/mysql/sample/sakila/1-sakila-schema.sql
    curl $SCHEMA_DOWNLOAD_LINK -o /tmp/1-sakila-schema.sql
    mysql -uroot -pSuperSecr3t < /tmp/1-sakila-schema.sql > /tmp/1.log

    DATA_DOWNLOAD_LINK=https://raw.githubusercontent.com/sondn98/hilt/master/kubernetes/databases/mysql/sample/sakila/2-sakila-data.sql
    curl $DATA_DOWNLOAD_LINK -o /tmp/2-sakila-data.sql
    mysql -uroot -pSuperSecr3t < /tmp/2-sakila-data.sql > /tmp/2.log

    rm -rf /tmp/*.sql

primary:
  name: primary
  persistence:
    enabled: false
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  service:
    type: ClusterIP
    ports:
      mysql: 3306
