version: '3'

tasks:

  start:
    cmds:
    - docker compose up -d --remove-orphans
  
  stop:
    cmds:
    - docker compose down

  shell:
    cmds:
    - echo "SuperSecr3t" | docker-compose exec -it postgresql psql -U postgres -W -d postgres
