replicaCount: 1

auth:
  createAdminUser: true
  adminUser:     dataops
  adminPassword: SuperSecr3t
  managementUser:     sondn
  managementPassword: SuperSecr3t

proxyAddressForwarding: true
serviceDiscovery:
  enabled: true

serviceAccount:
  create: true

rbac:
  create: true

pdb:
  create: true
  minAvailable: 1

service:
  type: ClusterIP
  ports:
    http: 8080

ingress:
  ingressClassName: nginx
  enabled: true
  tls: true
  hostname: keycloak.demo.com
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer

postgresql:
  enabled: false

externalDatabase:
  host: postgresql.postgresql.svc
  port: 5432
  user:     keycloak
  password: SuperSecr3t
  database: postgres

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

metrics:
  enabled: false
  serviceMonitor:
    enabled: true
