version: '3.7'

services:
  namenode:
    image: sondn1/hadoop-namenode:0.1.0-hadoop_3.3.1
    volumes:
      - namenode:/hadoop/dfs/name
    ports:
      - 9870:9870
    profiles:
      - hdfs
      - hadoop
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - local

  datanode:
    image: sondn1/hadoop-datanode:0.1.0-hadoop_3.3.1
    volumes:
      - datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    profiles:
      - hdfs
      - hadoop
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure
    networks:
      - local

  resourcemanager:
    image: sondn1/hadoop-resourcemanager:0.1.0-hadoop_3.3.1
    depends_on:
      - namenode
      - datanode
    profiles:
      - mapreduce
      - hadoop
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      disable: true
    networks:
      - local

  nodemanager:
    image: sondn1/hadoop-nodemanager:0.1.0-hadoop_3.3.1
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    profiles:
      - mapreduce
      - hadoop
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - local

  historyserver:
    image: sondn1/hadoop-historyserver:0.1.0-hadoop_3.3.1
    volumes:
      - historyserver:/hadoop/yarn/timeline
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    profiles:
      - mapreduce
      - hadoop
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - local

volumes:
  datanode:
  namenode:
  historyserver:

networks:
  local:
    external: true
