version: '3'

includes:

  base:
    taskfile: ./base/Taskfile.yml
    dir: ./base

  namenode:
    taskfile: ./components/namenode/Taskfile.yml
    dir: ./components/namenode

  datanode:
    taskfile: ./components/datanode/Taskfile.yml
    dir: ./components/datanode

  resourcemanager:
    taskfile: ./components/resourcemanager/Taskfile.yml
    dir: ./components/resourcemanager

  nodemanager:
    taskfile: ./components/nodemanager/Taskfile.yml
    dir: ./components/nodemanager

  historyserver:
    taskfile: ./components/historyserver/Taskfile.yml
    dir: ./components/historyserver

tasks:

  start:
    cmds:
    - docker compose --profile=hdfs up -d --remove-orphans

  stop:
    cmds:
    - docker compose --profile=hdfs down

  start-all:
    cmds:
    - docker compose --profile=hadoop up -d --remove-orphans

  stop-all:
    cmds:
    - docker compose --profile=hadoop down

  build:
    cmds:
    - task: base:build
    - task: namenode:build
    - task: datanode:build
    - task: resourcemanager:build
    - task: nodemanager:build
    - task: historyserver:build

  push:
    cmds:
    - task: base:push
    - task: namenode:push
    - task: datanode:push
    - task: resourcemanager:push
    - task: nodemanager:push
    - task: historyserver:push

  publish:
    cmds:
    - task: build
    - task: publish
