version: '3'

vars:
  DEFAULT_NETWORK: '{{.DEFAULT_NETWORK | default "local_net"}}'
  HADOOP_VERSION: '{{.HADOOP_VERSION | default "3.3.1"}}'
  HADOOP_BASE_VERSION: '{{.HADOOP_BASE_VERSION | default "0.1.0"}}'
  HADOOP_DATANODE_VERSION: '{{.HADOOP_DATANODE_VERSION | default "0.1.0"}}'
  HADOOP_NAMENODE_VERSION: '{{.HADOOP_NAMENODE_VERSION | default "0.1.0"}}'
  HADOOP_NODEMANAGER_VERSION: '{{.HADOOP_NODEMANAGER_VERSION | default "0.1.0"}}'
  HADOOP_RESOURCEMANAGER_VERSION: '{{.HADOOP_RESOURCEMANAGER_VERSION | default "0.1.0"}}'

tasks:

  start-all:
    cmds:
    - docker compose up -d --remove-orphans

  stop-all:
    cmds:
    - docker compose down

  start-hdfs:
    cmds:
    - docker compose up -d --remove-orphans --profile=hdfs

  stop-hdfs:
    cmds:
    - docker compose down --profile=hdfs

  build-base:
    dir: ./common
    cmds:
    - docker build --tag sondn1/hadoop-base:{{ .HADOOP_BASE_VERSION }}-hadoop_{{ .HADOOP_VERSION }} .
    # - docker push sondn1/hadoop-base:$HADOOP_BASE_VERSION-hadoop_$HADOOP_VERSION

  build-namenode:
    dir: ./components/namenode
    cmds:
    - docker build --tag sondn1/hadoop-namenode:{{ .HADOOP_NAMENODE_VERSION }}-hadoop_{{ .HADOOP_VERSION }} .
    # - docker push sondn1/hadoop-datanode:{{ .HADOOP_NAMENODE_VERSION }}-hadoop_{{ .HADOOP_VERSION }}

  build-datanode:
    dir: ./components/datanode
    cmds:
    - docker build --tag sondn1/hadoop-datanode:{{ .HADOOP_DATANODE_VERSION }}-hadoop_{{ .HADOOP_VERSION }} .
    # - docker push sondn1/hadoop-datanode:{{ .HADOOP_DATANODE_VERSION }}-hadoop_{{ .HADOOP_VERSION }}

  build-historyserver:
    dir: ./components/historyserver
    cmds:
    - docker build --tag sondn1/hadoop-historyserver:{{ .HADOOP_HISTORYSERVER_VERSION }}-hadoop_{{ .HADOOP_VERSION }} .
    # - docker push sondn1/hadoop-datanode:{{ .HADOOP_DATANODE_VERSION }}-hadoop_{{ .HADOOP_VERSION }}

  build-nodemanager:
    dir: ./components/nodemanager
    cmds:
    - docker build --tag sondn1/hadoop-nodemanager:{{ .HADOOP_NODEMANAGER_VERSION }}-hadoop_{{ .HADOOP_VERSION }} .
    # - docker push sondn1/hadoop-datanode:{{ .HADOOP_NODEMANAGER_VERSION }}-hadoop_{{ .HADOOP_VERSION }}

  build-resourcemanager:
    dir: ./components/resourcemanager
    cmds:
    - docker build --tag sondn1/hadoop-resourcemanager:{{ .HADOOP_RESOURCEMANAGER_VERSION }}-hadoop_{{ .HADOOP_VERSION }} .
    # - docker push sondn1/hadoop-datanode:{{ .HADOOP_RESOURCEMANAGER_VERSION }}-hadoop_{{ .HADOOP_VERSION }}
