image:
  repository: hub.teko.vn/dataops/hive
  tag: 3.1.3

hiveConfig:
  hive-site.xml:
    hive.metastore.event.db.notification.api.auth: false
    # https://prestosql.io/docs/current/connector/hive.html#metastore-configuration-for-avro
    metastore.storage.schema.reader.impl: org.apache.hadoop.hive.metastore.SerDeStorageSchemaReader
    # Enable cleaner threads to support Hive transactions
    # https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=82706483#HiveTransactions-Configuration
    hive.compactor.initiator.on: true
    hive.compactor.worker.threads: 1

metastore:
  replicas: 1

warehouse:
  dir: s3a://develop/vnshop-datalake/alluvial/.warehouse/

metrics:
  enabled: false
  port: 9028
  podMonitor:
    enabled: true

filesystem:
  s3a:
    enabled: true
    endpoint:  http://minio.minio.svc.cluster.local:9000/
    accessKey: admin
    secretKey: SuperSecr3t

postgresql:
  enabled: false

externalDatabase:
  type: postgres
  host: postgresql.postgresql.svc.cluster.local
  port: 5432
  database: hive-metastore-vnshop-datalake
  username: admin
  password: SuperSecr3t
