repositories:
- name: bitnami
  url:  https://charts.bitnami.com/bitnami
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

helmDefaults:
  wait: true
  force: true
  verify: true
  createNamespace: true
  timeout: 600

helmfiles:
# - path: compute/airflow/helmfile.yaml
# - path: compute/trino/helmfile.yaml
# - path: serving/keycloak/helmfile.yaml
# - path: serving/hive/helmfile.yaml
- path: serving/prometheus/helmfile.yaml
# - path: storage/postgresql/helmfile.yaml
# - path: storage/minio/helmfile.yaml
