version: '3'

vars:
  NAMESPACE: '{{.NAMESPACE | default "default"}}'
  RELEASE: '{{.RELEASE | default "funny"}}'
  VALUES: '{{.VALUES | default "./values.yaml"}}'

includes:
  trino:
    taskfile: ./compute/trino/Taskfile.yml
    dir: ./compute/trino

tasks:

  minikube-up:
    cmds:
    - minikube start --driver=docker
                     --mount
                     --mount-string="/data1/minikube:/data1"
                     --container-runtime=containerd
                     --memory 8192 --cpus 4
                     --nodes 1

  minikube-down:
    cmds:
    - minikube stop --all

  minikube-delete:
    cmds:
    - minikube delete

  deploy:
    cmds:
    - helmfile apply

  destroy:
    cmds:
    - helmfile destroy

  # task template -- name=<release_name>,layer=<layer>,...gen
  template:
    cmds:
    - helmfile --selector {{ .CLI_ARGS }} template --output-dir=./build

  clean:
    cmds:
    - for layer in */ ; do for platform in $layer ; do echo $layer/$platform ; done ; done

  diff:
    cmds:
    - helm diff upgrade {{.RELEASE}} .
        --namespace={{.NAMESPACE}}
        --values={{.VALUES}}
        --allow-unreleased

  apply:
    cmds:
    - helm upgrade --install {{.RELEASE}} .
        --namespace={{.NAMESPACE}}
        --values={{.VALUES}}
        --create-namespace

  show:
    cmds:
    - kubectl --namespace={{.NAMESPACE}} get pod
        -l app.kubernetes.io/instance={{.RELEASE}}
