image:
  repository: tchiotludo/akhq
  tag: "0.21.0"

secrets:
  akhq:
    connections:
      mini-kafka:
        properties:
          bootstrap.servers: "kafka:9092"
        schema-registry:
          url: "http://schema-registry.kafka.svc.cluster.local:8081"
          type: "confluent"
        connect:
          - name: "mini-debezium"
            url: "http://debezium-connect-api.kafka.svc.cluster.local:8083"

service:
  enabled: true
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  ingressClassName: nginx
  paths:
    - /
  hosts:
    - akhq.demo.com
