image:
  registry: docker.io
  repository: bitnami/schema-registry
  tag: 7.1.3-debian-11-r11

listeners: http://0.0.0.0:8081
avroCompatibilityLevel: backward

service:
  type: ClusterIP
  ports:
    http: 8081

##
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
startupProbe:
  enabled: false

kafka:
  enabled: false

externalKafka:
  brokers:
    - PLAINTEXT://kafka.kafka.svc.cluster.local:9092
