version: '3'

tasks:

  start:
    cmds:
    - docker compose up -d --remove-orphans
  
  stop:
    cmds:
    - docker compose down

  shell:
    cmds:
    - docker compose exec -it mysql mysql -uroot -pSuperSecr3t
