# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql:8.0
    command: 
      - --gtid-mode=ON
      - --enforce_gtid_consistency=ON
      - --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecr3t
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./sample/sakila-db:/docker-entrypoint-initdb.d/
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
