version: '3.7'

services:

  grafana:
    image: grafana/grafana
    user: "472"
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=SuperSecr3t
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  grafana_data:

networks:
  default:
    name: local_common_network
    external: true
