version: "3.8"

services:

  # TODO: a workaround to pre-create search indices

  datahub-gms:
    image: linkedin/datahub-gms:cf3db16
    # restart: unless-stopped
    ports:
      - 8084:8080
    environment:
      EBEAN_DATASOURCE_USERNAME: root
      EBEAN_DATASOURCE_PASSWORD: SuperSecr3t
      EBEAN_DATASOURCE_HOST: mysql:3306
      EBEAN_DATASOURCE_URL: jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2
      EBEAN_DATASOURCE_DRIVER: com.mysql.jdbc.Driver
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      KAFKA_SCHEMAREGISTRY_URL: http://schema-registry:8085
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ES_BULK_REFRESH_POLICY: WAIT_UNTIL
      NEO4J_HOST: http://neo4j:7474
      NEO4J_URI: bolt://neo4j
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: datahub
      JAVA_OPTS: >
        -Xms1g
        -Xmx1g
      ES_BULK_REFRESH_POLICY: WAIT_UNTIL
      GRAPH_SERVICE_DIFF_MODE_ENABLED: true
      GRAPH_SERVICE_IMPL: neo4j
      ENTITY_REGISTRY_CONFIG_PATH: /datahub/datahub-gms/resources/entity-registry.yml
      ENTITY_SERVICE_ENABLE_RETENTION: true
      MAE_CONSUMER_ENABLED: true
      MCE_CONSUMER_ENABLED: true
      PE_CONSUMER_ENABLED: true
      UI_INGESTION_ENABLED: true
      METADATA_SERVICE_AUTH_ENABLED: false
    networks:
      - local

  datahub-frontend-react:
    image: linkedin/datahub-frontend-react:cf3db16
    restart: unless-stopped
    ports:
      - 9099:9002
    environment:
      DATAHUB_GMS_HOST: datahub-gms
      DATAHUB_GMS_PORT: 8080
      DATAHUB_SECRET: SuperSecr3t
      DATAHUB_APP_VERSION: 1.0
      DATAHUB_PLAY_MEM_BUFFER_SIZE: 10MB
      JAVA_OPTS: >
        -Xms512m
        -Xmx512m
        -Dhttp.port=9002
        -Dconfig.file=datahub-frontend/conf/application.conf
        -Djava.security.auth.login.config=datahub-frontend/conf/jaas.conf
        -Dlogback.configurationFile=datahub-frontend/conf/logback.xml
        -Dlogback.debug=false -Dpidfile.path=/dev/null
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      DATAHUB_TRACKING_TOPIC: DataHubUsageEvent_v1
      ELASTIC_CLIENT_HOST: elasticsearch
      ELASTIC_CLIENT_PORT: 9200
    depends_on:
      - datahub-gms
    volumes:
      - ${HOME}/.datahub/plugins:/etc/datahub/plugins
    networks:
      - local

  datahub-actions:
    image: acryldata/datahub-actions:9187d0e
    restart: unless-stopped
    environment:
      DATAHUB_GMS_PROTOCOL: http
      DATAHUB_GMS_HOST: datahub-gms
      DATAHUB_GMS_PORT: 8080
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      SCHEMA_REGISTRY_URL: http://schema-registry:8085
      METADATA_AUDIT_EVENT_NAME: MetadataAuditEvent_v4
      METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME: MetadataChangeLog_Versioned_v1
      DATAHUB_SYSTEM_CLIENT_ID: datahub
      DATAHUB_SYSTEM_CLIENT_SECRET: SuperSecr3t
      KAFKA_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
    depends_on:
      - datahub-gms
    networks:
      - local

networks:
  local:
    external: true

networks:
  local:
    external: true
