version: "3.8"

services:

  datahub-gms:
    image: linkedin/datahub-gms:cf3db16
    restart: unless-stopped
    ports:
      - 8084:8080
    env_file:
      - ./config/gms-env.sh
    depends_on:
      - setup-kafka
      - setup-elasticsearch
    networks:
      - local

  datahub-frontend-react:
    image: linkedin/datahub-frontend-react:8b3056a
    restart: unless-stopped
    ports:
      - 9099:9002
    env_file:
      - ./config/frontend-env.sh
    depends_on:
      - datahub-gms
    volumes:
      - ${DOCKER_ROOT_DIR}/../bookshelf/draft/docker/datahub/plugins:/etc/datahub/plugins
    networks:
      - local

  datahub-actions:
    image: acryldata/datahub-actions:792a8a8
    restart: unless-stopped
    env_file:
      - ./config/actions-env.sh
    depends_on:
      - datahub-gms
    networks:
      - local

  setup-kafka:
    image: linkedin/datahub-kafka-setup:8b3056a
    env_file:
      - ./config/setup-kafka.sh
    networks:
      - local

  # This "container" is a workaround to pre-create search indices
  setup-elasticsearch:
    image: linkedin/datahub-elasticsearch-setup:8b3056a
    env_file:
      - ./config/setup-elasticsearch.sh
    networks:
      - local

networks:
  local:
    external: true

networks:
  local:
    external: true
