version: '3'

env:
  START_WITH_ESSENTIAL_SERVICE: '{{ .START_WITH_ESSENTIAL_SERVICE | default true }}'
  STOP_WITH_ESSENTIAL_SERVICE: '{{ .STOP_WITH_ESSENTIAL_SERVICE | default false }}'

tasks:

  start:
    cmds:
    - docker compose -f preparing.yml up -d --remove-orphans
    - sleep 5
    - docker compose up -d --remove-orphans

  stop:
    cmds:
    - docker compose down --volumes
