version: "2.5"

services:

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - local

volumes:
  zookeeper_data:

networks:
  local:
    external: true
