version: "2.5"

services:

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - local_common_network

volumes:
  zookeeper_data:

networks:
  local_common_network:
    external: true
