version: '2'

services:

  elasticsearch:
    image: elasticsearch:7.9.3
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xms256m -Xmx256m -Dlog4j2.formatMsgNoLookups=true"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - local

volumes:
  elasticsearch_data:

networks:
  local:
    external: true
