version: "3.7"

services:

  clickhouse:
    image: clickhouse/clickhouse-server:23.1.3.5-alpine
    ports:
    - 8123:8123  # HTTP interface
    - 9000:9000  # native TCP interface
    volumes:
    - ./sample/:/docker-entrypoint-initdb.d/
    - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile: 262144
    networks:
      - local

volumes:
  clickhouse_data:

networks:
  local:
    external: true
